name: Cancella Vecchie Run

on:
  workflow_dispatch: # Avvio manuale
  schedule:
    - cron: '0 0 * * 0' # Ogni domenica a mezzanotte

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Obbligatorio per poter cancellare
      contents: read
    steps:
      - name: Rimuovi le run dei workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_hours: 1
          retain_days: 30 # Mantiene le run degli ultimi 30 giorni (metti 0 per cancellare tutto)
          keep_minimum_runs: 0 # Numero minimo di run da mantenere comunque
